# Generated by Django 5.1.1 on 2024-09-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazzat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
